#!/bin/bash

shef apt newsbeuter

shef git "Install newsbeuter configuration" \
    --repository https://github.com/CaptainQuirk/.newsbeuter.git \
    --destination "$CONFIG_SRC_DIR/.newsbeuter"

shef file "Install X wrapper script" \
    --source "$RECIPE_DIR/files/x-newsbeuter" \
    --path "/usr/local/bin/x-newsbeuter" \
    --update \
    --sudo

shef file "Install tmuxinator configuration" \
    --source "$RECIPE_DIR/files/newsbeuter.yml" \
    --path "$HOME/.config/tmuxinator/newsbeuter.yml" \
    --update

shef file "Install tmuxinator configuration" \
    --source "$RECIPE_DIR/files/newsbeuter.desktop"  \
    --path  "$HOME/.local/share/applications/newsbeuter.desktop"\
    --update

shef file "Install tmuxinator configuration" \
    --source "$RECIPE_DIR/files/newsbeuter.png" \
    --path  "$HOME/.local/share/icons/newsbeuter.png"\
    --update
